name = "Spins"
uuid = "6b5dd1cd-8ee3-4435-8d48-ab3f27e8632d"
authors = ["abhirup-m <mukherjeeabhirup44@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
